### ISSUE TITLE
github repository naming convention

### ISSUE THREAD

**Issue by carlosalfarodev** [Codigo-Diverso/link-manager#1]
I noticed the name of the repository does not follow a common or popular naming convention. Would it be possible to change "Link-manager" to "link-manager" so that the URL looks clean and also the local project repository?
Here's a guide if you consider changing it.
https://docs.github.com/en/github/administering-a-repository/renaming-a-repository

**Comment by LeoRincon** [comment]
> I noticed the name of the repository does not follow a common or popular naming convention. Would it be possible to change "Link-manager" to "link-manager" so that the URL looks clean and also the local project repository?
> Here's a guide if you consider changing it.
> https://docs.github.com/en/github/administering-a-repository/renaming-a-repository

**Comment by LeoRincon** [comment]
> I noticed the name of the repository does not follow a common or popular naming convention. Would it be possible to change "Link-manager" to "link-manager" so that the URL looks clean and also the local project repository?
> Here's a guide if you consider changing it.
> https://docs.github.com/en/github/administering-a-repository/renaming-a-repository

Done! thank you.
